apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: open5gs-monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      
      - job_name: 'open5gs-amf'
        metrics_path: /metrics
        scheme: http
        static_configs:
          - targets: ['amf-metrics-open5gcore.apps.acmhub.narlabs.io']
            labels:
              service: 'open5gs-amf'
              component: '5g-core'
      
      - job_name: 'open5gs-smf'
        metrics_path: /metrics
        scheme: http
        static_configs:
          - targets: ['smf-metrics-open5gcore.apps.acmhub.narlabs.io']
            labels:
              service: 'open5gs-smf'
              component: '5g-core'