---
# OpenShift Template for Open5GS AUSF (Authentication Server Function)
# Author: Fatih E.NAR
# Date: 4/11/2075 
#
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: open5gs-ausf
  annotations:
    description: "Authentication Server Function (AUSF) for Open5GS"
    tags: "5g,open5gs,ausf"
    openshift.io/display-name: "Open5GS AUSF"
    openshift.io/documentation-url: "https://open5gs.org"
    openshift.io/support-url: "https://github.com/open5gs/open5gs/issues"
    iconClass: "icon-5g"
parameters:
- name: NAME
  description: The name assigned to all of the objects defined in this template.
  displayName: Name
  required: true
  value: "open5gs-ausf"
- name: NAMESPACE
  description: The OpenShift Namespace where the ImageStream resides.
  displayName: Namespace
  required: true
  value: "open5gcore"
- name: IMAGE_REGISTRY
  description: The registry for the AUSF image
  displayName: Image Registry
  required: true
  value: "docker.io"
- name: IMAGE_REPOSITORY
  description: The repository for the AUSF image
  displayName: Image Repository
  required: true
  value: "gradiant/open5gs"
- name: IMAGE_TAG
  description: The image tag to be used
  displayName: Image Tag
  required: true
  value: "2.7.5"
- name: NRF_SVC
  description: NRF Service Name
  displayName: NRF Service
  required: true
  value: "open5gs-nrf"
- name: UDM_SVC
  description: UDM Service Name
  displayName: UDM Service
  required: true
  value: "open5gs-udm"
objects:
- apiVersion: v1
  kind: Service
  metadata:
    name: ${NAME}
    labels:
      app: ${NAME}
      app.kubernetes.io/name: ${NAME}
      app.kubernetes.io/part-of: open5gcore
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "9090"
  spec:
    selector:
      app: ${NAME}
    ports:
    - name: sbi
      port: 80
      targetPort: 7781
      protocol: TCP
    - name: metrics
      port: 9090
      targetPort: 9090
      protocol: TCP
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: ${NAME}
    labels:
      app: ${NAME}
      app.kubernetes.io/name: ${NAME}
      app.kubernetes.io/part-of: open5gcore
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: ${NAME}
    strategy:
      type: RollingUpdate
    template:
      metadata:
        labels:
          app: ${NAME}
          app.kubernetes.io/name: ${NAME}
          app.kubernetes.io/part-of: open5gcore
        annotations:
          prometheus.io/scrape: "true" 
          prometheus.io/port: "9090"
      spec:
        securityContext:
          runAsUser: 0
          privileged: true
        containers:
        - name: ausf
          image: ${IMAGE_REGISTRY}/${IMAGE_REPOSITORY}:${IMAGE_TAG}
          imagePullPolicy: IfNotPresent
          command: ["open5gs-ausfd", "-c", "/open5gs/config-map/ausf.yaml"]
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            # Force HTTP/1.1 for compatibility
            - name: HTTP2_DISABLE
              value: "true"
          ports:
            - name: sbi
              containerPort: 7781
              protocol: TCP
            - name: metrics
              containerPort: 9090
              protocol: TCP
          securityContext:
            privileged: true
            capabilities:
              add: ["NET_ADMIN", "NET_RAW", "NET_BIND_SERVICE"]
          volumeMounts:
            - name: config-volume
              mountPath: /open5gs/config-map
            - name: shared-data
              mountPath: /open5gs/data
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            tcpSocket:
              port: 7781
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 7781
            initialDelaySeconds: 5
            periodSeconds: 5
        volumes:
          - name: config-volume
            configMap:
              name: ${NAME}-config
          - name: shared-data
            emptyDir: {}
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: ${NAME}-config
    labels:
      app: ${NAME}
      app.kubernetes.io/name: ${NAME}
      app.kubernetes.io/part-of: open5gcore
  data:
    ausf.yaml: |
      logger:
        level: debug
        domain: core

      # AUSF Configuration
      ausf:
        sbi:
          server:
            - dev: eth0
              port: 7781
              http2: false
          client:
            http2: false
            nrf:
              - uri: http://open5gs-nrf.open5gcore.svc.cluster.local:80
            amf:
              - uri: http://open5gs-amf.open5gcore.svc.cluster.local:80
            udm:
              - uri: http://open5gs-udm.open5gcore.svc.cluster.local:80
- apiVersion: v1
  kind: Route
  metadata:
    name: ${NAME}
    labels:
      app: ${NAME}
      app.kubernetes.io/name: ${NAME}
      app.kubernetes.io/part-of: open5gcore
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "9090"
  spec:
    path: /metrics
    to:
      kind: Service
      name: ${NAME}
    port:
      targetPort: metrics
    wildcardPolicy: None