---
# OpenShift Template for Open5GS UPF (User Plane Function)
# Author: Fatih E.NAR
# Date: 4/11/2075 
#
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: open5gs-upf
  annotations:
    description: "User Plane Function (UPF) for Open5GS"
    tags: "5g,open5gs,upf"
    openshift.io/display-name: "Open5GS UPF"
    openshift.io/documentation-url: "https://open5gs.org"
    openshift.io/support-url: "https://github.com/open5gs/open5gs/issues"
    iconClass: "icon-5g"
parameters:
- name: NAME
  description: The name assigned to all of the objects defined in this template.
  displayName: Name
  required: true
  value: "open5gs-upf"
- name: NAMESPACE
  description: The OpenShift Namespace where the ImageStream resides.
  displayName: Namespace
  required: true
  value: "open5gcore"
- name: IMAGE_REGISTRY
  description: The registry for the UPF image
  displayName: Image Registry
  required: true
  value: "docker.io"
- name: IMAGE_REPOSITORY
  description: The repository for the UPF image
  displayName: Image Repository
  required: true
  value: "gradiant/open5gs"
- name: IMAGE_TAG
  description: The image tag to be used
  displayName: Image Tag
  required: true
  value: "2.7.5"
objects:
- apiVersion: v1
  kind: Service
  metadata:
    name: ${NAME}
    labels:
      app: ${NAME}
      app.kubernetes.io/name: ${NAME}
      app.kubernetes.io/part-of: open5gcore
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "9090"
  spec:
    selector:
      app: ${NAME}
    ports:
    - name: pfcp
      port: 8805
      targetPort: 8805
      protocol: UDP
    - name: gtpu
      port: 2152
      targetPort: 2152
      protocol: UDP
    - name: metrics
      port: 9090
      targetPort: 9090
      protocol: TCP
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: ${NAME}
    labels:
      app: ${NAME}
      app.kubernetes.io/name: ${NAME}
      app.kubernetes.io/part-of: open5gcore
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: ${NAME}
    strategy:
      type: RollingUpdate
    template:
      metadata:
        labels:
          app: ${NAME}
          app.kubernetes.io/name: ${NAME}
          app.kubernetes.io/part-of: open5gcore
        annotations:
          prometheus.io/scrape: "true" 
          prometheus.io/port: "9090"
      spec:
        securityContext:
          runAsUser: 0
          privileged: true
        containers:
        - name: upf
          image: ${IMAGE_REGISTRY}/${IMAGE_REPOSITORY}:${IMAGE_TAG}
          imagePullPolicy: IfNotPresent
          command: ["open5gs-upfd", "-c", "/open5gs/config-map/upf.yaml"]
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - name: pfcp
              containerPort: 8805
              protocol: UDP
            - name: gtpu
              containerPort: 2152
              protocol: UDP
            - name: metrics
              containerPort: 9090
              protocol: TCP
          securityContext:
            privileged: true
            capabilities:
              add: ["NET_ADMIN", "NET_RAW", "NET_BIND_SERVICE"]
          volumeMounts:
            - name: config-volume
              mountPath: /open5gs/config-map
            - name: shared-data
              mountPath: /open5gs/data
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            exec:
              command:
                - pgrep
                - -f
                - open5gs-upfd
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - pgrep
                - -f
                - open5gs-upfd
            initialDelaySeconds: 5
            periodSeconds: 5
        volumes:
          - name: config-volume
            configMap:
              name: ${NAME}-config
          - name: shared-data
            emptyDir: {}
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: ${NAME}-config
    labels:
      app: ${NAME}
      app.kubernetes.io/name: ${NAME}
      app.kubernetes.io/part-of: open5gcore
  data:
    upf.yaml: |
      logger:
        level: debug
        domain: core

      # UPF Configuration
      upf:
        pfcp:
          server:
            - dev: eth0
          client:
        gtpu:
          server:
            - dev: eth0
        metrics:
          server:
            - dev: eth0
              port: 9090
        session:
          - subnet: 10.45.0.0/16
            gateway: 10.45.0.1
            dnn: internet
            dev: ogstun
            mask: 16
            createDev: true
            enableNAT: true
- apiVersion: v1
  kind: Route
  metadata:
    name: ${NAME}
    labels:
      app: ${NAME}
      app.kubernetes.io/name: ${NAME}
      app.kubernetes.io/part-of: open5gcore
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "9090"
  spec:
    path: /metrics
    to:
      kind: Service
      name: ${NAME}
    port:
      targetPort: metrics
    wildcardPolicy: None
