---
# OpenShift Template for Open5GS SMF (Session Management Function)
# Author: Fatih E.NAR
# Date: 4/11/2075 
#
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: open5gs-smf
  annotations:
    description: "Session Management Function (SMF) for Open5GS"
    tags: "5g,open5gs,smf"
    openshift.io/display-name: "Open5GS SMF"
    openshift.io/documentation-url: "https://open5gs.org"
    openshift.io/support-url: "https://github.com/open5gs/open5gs/issues"
    iconClass: "icon-5g"
parameters:
- name: NAME
  description: The name assigned to all of the objects defined in this template.
  displayName: Name
  required: true
  value: "open5gs-smf"
- name: NAMESPACE
  description: The OpenShift Namespace where the ImageStream resides.
  displayName: Namespace
  required: true
  value: "open5gcore"
- name: IMAGE_REGISTRY
  description: The registry for the SMF image
  displayName: Image Registry
  required: true
  value: "docker.io"
- name: IMAGE_REPOSITORY
  description: The repository for the SMF image
  displayName: Image Repository
  required: true
  value: "gradiant/open5gs"
- name: IMAGE_TAG
  description: The image tag to be used
  displayName: Image Tag
  required: true
  value: "2.7.5"
- name: MNC
  description: Mobile Network Code
  displayName: MNC
  required: true
  value: "70"
- name: MCC
  description: Mobile Country Code
  displayName: MCC
  required: true
  value: "999"
- name: UPF_SVC
  description: UPF Service Name
  displayName: UPF Service
  required: true
  value: "open5gs-upf"
- name: NRF_SVC
  description: NRF Service Name
  displayName: NRF Service
  required: true
  value: "open5gs-nrf"
objects:
- apiVersion: v1
  kind: Service
  metadata:
    name: ${NAME}
    labels:
      app: ${NAME}
      app.kubernetes.io/name: ${NAME}
      app.kubernetes.io/part-of: open5gcore
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "9090"
  spec:
    selector:
      app: ${NAME}
    ports:
    - name: sbi
      port: 80
      targetPort: 7778
      protocol: TCP
    - name: pfcp
      port: 8805
      targetPort: 8805
      protocol: UDP
    - name: gtpc
      port: 2123
      targetPort: 2123
      protocol: UDP
    - name: metrics
      port: 9090
      targetPort: 9090
      protocol: TCP
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: ${NAME}
    labels:
      app: ${NAME}
      app.kubernetes.io/name: ${NAME}
      app.kubernetes.io/part-of: open5gcore
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: ${NAME}
    strategy:
      type: RollingUpdate
    template:
      metadata:
        labels:
          app: ${NAME}
          app.kubernetes.io/name: ${NAME}
          app.kubernetes.io/part-of: open5gcore
        annotations:
          prometheus.io/scrape: "true" 
          prometheus.io/port: "9090"
      spec:
        securityContext:
          runAsUser: 0
          privileged: true
        containers:
        - name: smf
          image: ${IMAGE_REGISTRY}/${IMAGE_REPOSITORY}:${IMAGE_TAG}
          imagePullPolicy: IfNotPresent
          command: ["open5gs-smfd", "-c", "/open5gs/config-map/smf.yaml"]
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            # Force HTTP/1.1 for compatibility
            - name: HTTP2_DISABLE
              value: "true"
          ports:
            - name: sbi
              containerPort: 7778
              protocol: TCP
            - name: pfcp
              containerPort: 8805
              protocol: UDP
            - name: gtpc
              containerPort: 2123
              protocol: UDP
            - name: metrics
              containerPort: 9090
              protocol: TCP
          securityContext:
            privileged: true
            capabilities:
              add: ["NET_ADMIN", "NET_RAW", "NET_BIND_SERVICE"]
          volumeMounts:
            - name: config-volume
              mountPath: /open5gs/config-map
            - name: shared-data
              mountPath: /open5gs/data
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          # Use TCP as initial probe instead of HTTP to avoid protocol issues
          livenessProbe:
            tcpSocket:
              port: 7778
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 7778
            initialDelaySeconds: 5
            periodSeconds: 5
        volumes:
          - name: config-volume
            configMap:
              name: ${NAME}-config
          - name: shared-data
            emptyDir: {}
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: ${NAME}-config
    labels:
      app: ${NAME}
      app.kubernetes.io/name: ${NAME}
      app.kubernetes.io/part-of: open5gcore
  data:
    smf.yaml: |
      logger:
        level: debug
        domain: core
    
      # SMF Configuration
      smf:
        sbi:
          server:
            - dev: eth0
              port: 7778
              http2: false
          client:
            http2: false
            nrf:
              - uri: http://open5gs-nrf.open5gcore.svc.cluster.local
                http2: false
        pfcp:
          server:
            - dev: eth0
          client:
            upf:
              - address: open5gs-upf.open5gcore.svc.cluster.local
        gtpc:
          server:
            - dev: eth0
        gtpu:
          server:
            - dev: eth0
        metrics:
          server:
            - dev: eth0
              port: 9090
        dns:
          - 8.8.8.8
          - 8.8.4.4
        session:
          - subnet: 10.45.0.0/16
            gateway: 10.45.0.1
            dnn: internet
- apiVersion: v1
  kind: Route
  metadata:
    name: ${NAME}
    labels:
      app: ${NAME}
      app.kubernetes.io/name: ${NAME}
      app.kubernetes.io/part-of: open5gcore
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "9090"
  spec:
    path: /metrics
    to:
      kind: Service
      name: ${NAME}
    port:
      targetPort: metrics
    wildcardPolicy: None

